"""Command line interface of the Lazy Jones recompiler.

  python3 tools/ljrecomp build --game FILE --out DIR
      Read the game from FILE (.d64 or .prg), recompile it with the code map
      and write the C sources (game image + recompiled code) into DIR.

  python3 tools/ljrecomp codemap --game FILE --trace T [T ...] --out JSON
      Build a code map from explorer traces (host/ljexplore).

  python3 tools/ljrecomp disasm --game FILE --out FILE.asm
      Write a commented disassembly of the game (local use only: it
      contains the game code, do not publish it).
"""
import argparse
import json
import os
import sys

if __package__ in (None, ''):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    __package__ = 'ljrecomp'

from ljrecomp import analyze, codegen, image  # noqa: E402
from ljrecomp.opcodes import OPCODES  # noqa: E402
from ljrecomp.trace import Trace  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_CODEMAP = os.path.join(HERE, 'data', 'lazyjones_codemap.json')

HEADER = ('/* Generated by tools/ljrecomp from the game file you supplied.\n'
          ' * It contains the game: do not commit or distribute this file. */')


def place(img, info):
    mem = bytearray(0x10000)
    mem[info['load']:info['load'] + len(img)] = img
    return mem


def cmd_build(args):
    img, info = image.load_game(args.game, fix_texts=not args.no_text_fix)
    mem = place(img, info)
    code = analyze.load(args.codemap)
    lo, hi = info['load'], info['load'] + len(img)
    kept = {}
    dropped = 0
    for a, fl in code.items():
        op = mem[a]
        o = OPCODES[op]
        if not analyze.compilable(op) or o['undoc'] or a < lo or a + o['len'] > hi:
            dropped += 1
            continue
        kept[a] = fl
    if dropped:
        print('warning: %d code map entries do not decode in this image; '
              'they will run in the interpreter' % dropped)
    os.makedirs(args.out, exist_ok=True)
    with open(os.path.join(args.out, 'lj_recomp.c'), 'w') as f:
        f.write(codegen.generate_recomp(mem, kept, HEADER))
    with open(os.path.join(args.out, 'lj_game_data.c'), 'w') as f:
        f.write(codegen.generate_data(img, info, kept, HEADER))
    with open(os.path.join(args.out, 'lj_game_info.json'), 'w') as f:
        json.dump(dict(info, compiled_instructions=len(kept)), f, indent=1)
    print('recompiled %d instructions into %s' % (len(kept), args.out))
    return 0


def cmd_codemap(args):
    img, info = image.load_game(args.game, fix_texts=False)
    mem = place(img, info)
    traces = [Trace.load(p) for p in args.trace]
    code, merged = analyze.from_traces(traces)
    traced = len(code)
    mismatch = 0
    for a in list(code):
        n = OPCODES[mem[a]]['len']
        first = merged.first[a]
        if mem[a] != first[0]:
            del code[a]          # different code at run time than in the file
            mismatch += 1
        elif any(mem[a + i] != first[i] for i in range(1, n)):
            code[a] |= analyze.DYN
    added = analyze.extend_static(code, mem, merged) if not args.no_static else 0
    analyze.save(args.out, code, info)
    dyn = sum(1 for v in code.values() if v & analyze.DYN)
    print('code map: %d traced, %d added by static analysis, %d with run time operands, '
          '%d dropped (opcode differs from the file)' % (traced, added, dyn, mismatch))
    return 0


def cmd_disasm(args):
    img, info = image.load_game(args.game, fix_texts=False)
    mem = place(img, info)
    code = analyze.load(args.codemap)
    with open(args.out, 'w') as f:
        f.write('; Lazy Jones (C64) - disassembly of the code map. Local use only.\n')
        a = info['load']
        end = info['load'] + len(img)
        while a < end:
            if a in code:
                n = OPCODES[mem[a]]['len']
                tag = ' ; operand modified at run time' if code[a] & analyze.DYN else ''
                f.write('%04X  %-9s %s%s\n' % (a, ' '.join('%02X' % mem[a + i] for i in range(n)),
                                              codegen.disasm(mem, a), tag))
                a += n
            else:
                f.write('%04X  .byte $%02X\n' % (a, mem[a]))
                a += 1
    print('wrote', args.out)
    return 0


def main(argv=None):
    p = argparse.ArgumentParser(prog='ljrecomp')
    sub = p.add_subparsers(dest='cmd', required=True)
    b = sub.add_parser('build')
    b.add_argument('--game', required=True)
    b.add_argument('--out', required=True)
    b.add_argument('--codemap', default=DEFAULT_CODEMAP)
    b.add_argument('--no-text-fix', action='store_true')
    c = sub.add_parser('codemap')
    c.add_argument('--game', required=True)
    c.add_argument('--trace', nargs='+', required=True)
    c.add_argument('--out', required=True)
    c.add_argument('--no-static', action='store_true')
    d = sub.add_parser('disasm')
    d.add_argument('--game', required=True)
    d.add_argument('--out', required=True)
    d.add_argument('--codemap', default=DEFAULT_CODEMAP)
    args = p.parse_args(argv)
    try:
        return {'build': cmd_build, 'codemap': cmd_codemap, 'disasm': cmd_disasm}[args.cmd](args)
    except image.GameFileError as e:
        print('error:', e, file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
