/* Generated by tools/gen_cpu_ops.py from tools/ljrecomp/opcodes.py.
 * Do not edit by hand. See runtime/cpu_ops.h for the helpers. */
#ifndef LJ_CPU_OPS_GEN_H
#define LJ_CPU_OPS_GEN_H

/* 01 ORA izx */
#define OPC_01(o_) do { uint8_t p_ = (uint8_t)((o_) + C.cpu.x); uint16_t ea_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint8_t m_ = RD(ea_, 5); op_ora(m_); C.clk += 6; } while (0)
/* 03 SLO izx */
#define OPC_03(o_) do { uint8_t p_ = (uint8_t)((o_) + C.cpu.x); uint16_t ea_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint8_t m_ = RD(ea_, 5); DWR(ea_, m_, 6); m_ = op_slo(m_); WR(ea_, m_, 7); C.clk += 8; } while (0)
/* 04 NOP zp */
#define OPC_04(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); (void)m_; C.clk += 3; } while (0)
/* 05 ORA zp */
#define OPC_05(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); op_ora(m_); C.clk += 3; } while (0)
/* 06 ASL zp */
#define OPC_06(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); m_ = op_asl(m_); ZWR(ea_, m_); C.clk += 5; } while (0)
/* 07 SLO zp */
#define OPC_07(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); m_ = op_slo(m_); ZWR(ea_, m_); C.clk += 5; } while (0)
/* 08 PHP imp */
#define OPC_08() do { cpu_push((uint8_t)(cpu_get_p() | 0x30)); C.clk += 3; } while (0)
/* 09 ORA imm */
#define OPC_09(o_) do { uint8_t m_ = (uint8_t)(o_); op_ora(m_); C.clk += 2; } while (0)
/* 0A ASL acc */
#define OPC_0A() do { C.cpu.a = op_asl(C.cpu.a); C.clk += 2; } while (0)
/* 0B ANC imm */
#define OPC_0B(o_) do { uint8_t m_ = (uint8_t)(o_); op_and(m_); C.cpu.fc = C.cpu.a >> 7; C.clk += 2; } while (0)
/* 0C NOP abs */
#define OPC_0C(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); (void)m_; C.clk += 4; } while (0)
/* 0D ORA abs */
#define OPC_0D(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); op_ora(m_); C.clk += 4; } while (0)
/* 0E ASL abs */
#define OPC_0E(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); DWR(ea_, m_, 4); m_ = op_asl(m_); WR(ea_, m_, 5); C.clk += 6; } while (0)
/* 0F SLO abs */
#define OPC_0F(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); DWR(ea_, m_, 4); m_ = op_slo(m_); WR(ea_, m_, 5); C.clk += 6; } while (0)
/* 11 ORA izy */
#define OPC_11(o_) do { uint8_t p_ = (uint8_t)(o_); uint16_t b_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 4); uint8_t m_ = RD(ea_, 4 + px_); op_ora(m_); C.clk += 5 + px_; } while (0)
/* 13 SLO izy */
#define OPC_13(o_) do { uint8_t p_ = (uint8_t)(o_); uint16_t b_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 4); uint8_t m_ = RD(ea_, 5); DWR(ea_, m_, 6); m_ = op_slo(m_); WR(ea_, m_, 7); C.clk += 8; } while (0)
/* 14 NOP zpx */
#define OPC_14(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); (void)m_; C.clk += 4; } while (0)
/* 15 ORA zpx */
#define OPC_15(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); op_ora(m_); C.clk += 4; } while (0)
/* 16 ASL zpx */
#define OPC_16(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); m_ = op_asl(m_); ZWR(ea_, m_); C.clk += 6; } while (0)
/* 17 SLO zpx */
#define OPC_17(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); m_ = op_slo(m_); ZWR(ea_, m_); C.clk += 6; } while (0)
/* 18 CLC imp */
#define OPC_18() do { C.cpu.fc = 0; C.clk += 2; } while (0)
/* 19 ORA aby */
#define OPC_19(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); op_ora(m_); C.clk += 4 + px_; } while (0)
/* 1A NOP imp */
#define OPC_1A() do {  C.clk += 2; } while (0)
/* 1B SLO aby */
#define OPC_1B(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_slo(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* 1C NOP abx */
#define OPC_1C(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); (void)m_; C.clk += 4 + px_; } while (0)
/* 1D ORA abx */
#define OPC_1D(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); op_ora(m_); C.clk += 4 + px_; } while (0)
/* 1E ASL abx */
#define OPC_1E(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_asl(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* 1F SLO abx */
#define OPC_1F(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_slo(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* 21 AND izx */
#define OPC_21(o_) do { uint8_t p_ = (uint8_t)((o_) + C.cpu.x); uint16_t ea_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint8_t m_ = RD(ea_, 5); op_and(m_); C.clk += 6; } while (0)
/* 23 RLA izx */
#define OPC_23(o_) do { uint8_t p_ = (uint8_t)((o_) + C.cpu.x); uint16_t ea_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint8_t m_ = RD(ea_, 5); DWR(ea_, m_, 6); m_ = op_rla(m_); WR(ea_, m_, 7); C.clk += 8; } while (0)
/* 24 BIT zp */
#define OPC_24(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); op_bit(m_); C.clk += 3; } while (0)
/* 25 AND zp */
#define OPC_25(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); op_and(m_); C.clk += 3; } while (0)
/* 26 ROL zp */
#define OPC_26(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); m_ = op_rol(m_); ZWR(ea_, m_); C.clk += 5; } while (0)
/* 27 RLA zp */
#define OPC_27(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); m_ = op_rla(m_); ZWR(ea_, m_); C.clk += 5; } while (0)
/* 28 PLP imp */
#define OPC_28() do { cpu_set_p(cpu_pull()); C.clk += 4; cpu_irq_recheck_delayed(); } while (0)
/* 29 AND imm */
#define OPC_29(o_) do { uint8_t m_ = (uint8_t)(o_); op_and(m_); C.clk += 2; } while (0)
/* 2A ROL acc */
#define OPC_2A() do { C.cpu.a = op_rol(C.cpu.a); C.clk += 2; } while (0)
/* 2B ANC imm */
#define OPC_2B(o_) do { uint8_t m_ = (uint8_t)(o_); op_and(m_); C.cpu.fc = C.cpu.a >> 7; C.clk += 2; } while (0)
/* 2C BIT abs */
#define OPC_2C(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); op_bit(m_); C.clk += 4; } while (0)
/* 2D AND abs */
#define OPC_2D(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); op_and(m_); C.clk += 4; } while (0)
/* 2E ROL abs */
#define OPC_2E(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); DWR(ea_, m_, 4); m_ = op_rol(m_); WR(ea_, m_, 5); C.clk += 6; } while (0)
/* 2F RLA abs */
#define OPC_2F(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); DWR(ea_, m_, 4); m_ = op_rla(m_); WR(ea_, m_, 5); C.clk += 6; } while (0)
/* 31 AND izy */
#define OPC_31(o_) do { uint8_t p_ = (uint8_t)(o_); uint16_t b_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 4); uint8_t m_ = RD(ea_, 4 + px_); op_and(m_); C.clk += 5 + px_; } while (0)
/* 33 RLA izy */
#define OPC_33(o_) do { uint8_t p_ = (uint8_t)(o_); uint16_t b_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 4); uint8_t m_ = RD(ea_, 5); DWR(ea_, m_, 6); m_ = op_rla(m_); WR(ea_, m_, 7); C.clk += 8; } while (0)
/* 34 NOP zpx */
#define OPC_34(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); (void)m_; C.clk += 4; } while (0)
/* 35 AND zpx */
#define OPC_35(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); op_and(m_); C.clk += 4; } while (0)
/* 36 ROL zpx */
#define OPC_36(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); m_ = op_rol(m_); ZWR(ea_, m_); C.clk += 6; } while (0)
/* 37 RLA zpx */
#define OPC_37(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); m_ = op_rla(m_); ZWR(ea_, m_); C.clk += 6; } while (0)
/* 38 SEC imp */
#define OPC_38() do { C.cpu.fc = 1; C.clk += 2; } while (0)
/* 39 AND aby */
#define OPC_39(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); op_and(m_); C.clk += 4 + px_; } while (0)
/* 3A NOP imp */
#define OPC_3A() do {  C.clk += 2; } while (0)
/* 3B RLA aby */
#define OPC_3B(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_rla(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* 3C NOP abx */
#define OPC_3C(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); (void)m_; C.clk += 4 + px_; } while (0)
/* 3D AND abx */
#define OPC_3D(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); op_and(m_); C.clk += 4 + px_; } while (0)
/* 3E ROL abx */
#define OPC_3E(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_rol(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* 3F RLA abx */
#define OPC_3F(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_rla(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* 41 EOR izx */
#define OPC_41(o_) do { uint8_t p_ = (uint8_t)((o_) + C.cpu.x); uint16_t ea_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint8_t m_ = RD(ea_, 5); op_eor(m_); C.clk += 6; } while (0)
/* 43 SRE izx */
#define OPC_43(o_) do { uint8_t p_ = (uint8_t)((o_) + C.cpu.x); uint16_t ea_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint8_t m_ = RD(ea_, 5); DWR(ea_, m_, 6); m_ = op_sre(m_); WR(ea_, m_, 7); C.clk += 8; } while (0)
/* 44 NOP zp */
#define OPC_44(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); (void)m_; C.clk += 3; } while (0)
/* 45 EOR zp */
#define OPC_45(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); op_eor(m_); C.clk += 3; } while (0)
/* 46 LSR zp */
#define OPC_46(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); m_ = op_lsr(m_); ZWR(ea_, m_); C.clk += 5; } while (0)
/* 47 SRE zp */
#define OPC_47(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); m_ = op_sre(m_); ZWR(ea_, m_); C.clk += 5; } while (0)
/* 48 PHA imp */
#define OPC_48() do { cpu_push(C.cpu.a); C.clk += 3; } while (0)
/* 49 EOR imm */
#define OPC_49(o_) do { uint8_t m_ = (uint8_t)(o_); op_eor(m_); C.clk += 2; } while (0)
/* 4A LSR acc */
#define OPC_4A() do { C.cpu.a = op_lsr(C.cpu.a); C.clk += 2; } while (0)
/* 4B ALR imm */
#define OPC_4B(o_) do { uint8_t m_ = (uint8_t)(o_); C.cpu.a &= m_; C.cpu.a = op_lsr(C.cpu.a); C.clk += 2; } while (0)
/* 4D EOR abs */
#define OPC_4D(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); op_eor(m_); C.clk += 4; } while (0)
/* 4E LSR abs */
#define OPC_4E(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); DWR(ea_, m_, 4); m_ = op_lsr(m_); WR(ea_, m_, 5); C.clk += 6; } while (0)
/* 4F SRE abs */
#define OPC_4F(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); DWR(ea_, m_, 4); m_ = op_sre(m_); WR(ea_, m_, 5); C.clk += 6; } while (0)
/* 51 EOR izy */
#define OPC_51(o_) do { uint8_t p_ = (uint8_t)(o_); uint16_t b_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 4); uint8_t m_ = RD(ea_, 4 + px_); op_eor(m_); C.clk += 5 + px_; } while (0)
/* 53 SRE izy */
#define OPC_53(o_) do { uint8_t p_ = (uint8_t)(o_); uint16_t b_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 4); uint8_t m_ = RD(ea_, 5); DWR(ea_, m_, 6); m_ = op_sre(m_); WR(ea_, m_, 7); C.clk += 8; } while (0)
/* 54 NOP zpx */
#define OPC_54(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); (void)m_; C.clk += 4; } while (0)
/* 55 EOR zpx */
#define OPC_55(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); op_eor(m_); C.clk += 4; } while (0)
/* 56 LSR zpx */
#define OPC_56(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); m_ = op_lsr(m_); ZWR(ea_, m_); C.clk += 6; } while (0)
/* 57 SRE zpx */
#define OPC_57(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); m_ = op_sre(m_); ZWR(ea_, m_); C.clk += 6; } while (0)
/* 58 CLI imp */
#define OPC_58() do { C.cpu.fi = 0; C.clk += 2; cpu_irq_recheck_delayed(); } while (0)
/* 59 EOR aby */
#define OPC_59(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); op_eor(m_); C.clk += 4 + px_; } while (0)
/* 5A NOP imp */
#define OPC_5A() do {  C.clk += 2; } while (0)
/* 5B SRE aby */
#define OPC_5B(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_sre(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* 5C NOP abx */
#define OPC_5C(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); (void)m_; C.clk += 4 + px_; } while (0)
/* 5D EOR abx */
#define OPC_5D(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); op_eor(m_); C.clk += 4 + px_; } while (0)
/* 5E LSR abx */
#define OPC_5E(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_lsr(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* 5F SRE abx */
#define OPC_5F(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_sre(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* 61 ADC izx */
#define OPC_61(o_) do { uint8_t p_ = (uint8_t)((o_) + C.cpu.x); uint16_t ea_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint8_t m_ = RD(ea_, 5); op_adc(m_); C.clk += 6; } while (0)
/* 63 RRA izx */
#define OPC_63(o_) do { uint8_t p_ = (uint8_t)((o_) + C.cpu.x); uint16_t ea_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint8_t m_ = RD(ea_, 5); DWR(ea_, m_, 6); m_ = op_rra(m_); WR(ea_, m_, 7); C.clk += 8; } while (0)
/* 64 NOP zp */
#define OPC_64(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); (void)m_; C.clk += 3; } while (0)
/* 65 ADC zp */
#define OPC_65(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); op_adc(m_); C.clk += 3; } while (0)
/* 66 ROR zp */
#define OPC_66(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); m_ = op_ror(m_); ZWR(ea_, m_); C.clk += 5; } while (0)
/* 67 RRA zp */
#define OPC_67(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); m_ = op_rra(m_); ZWR(ea_, m_); C.clk += 5; } while (0)
/* 68 PLA imp */
#define OPC_68() do { C.cpu.a = cpu_pull(); SETNZ(C.cpu.a); C.clk += 4; } while (0)
/* 69 ADC imm */
#define OPC_69(o_) do { uint8_t m_ = (uint8_t)(o_); op_adc(m_); C.clk += 2; } while (0)
/* 6A ROR acc */
#define OPC_6A() do { C.cpu.a = op_ror(C.cpu.a); C.clk += 2; } while (0)
/* 6B ARR imm */
#define OPC_6B(o_) do { uint8_t m_ = (uint8_t)(o_); op_arr(m_); C.clk += 2; } while (0)
/* 6D ADC abs */
#define OPC_6D(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); op_adc(m_); C.clk += 4; } while (0)
/* 6E ROR abs */
#define OPC_6E(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); DWR(ea_, m_, 4); m_ = op_ror(m_); WR(ea_, m_, 5); C.clk += 6; } while (0)
/* 6F RRA abs */
#define OPC_6F(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); DWR(ea_, m_, 4); m_ = op_rra(m_); WR(ea_, m_, 5); C.clk += 6; } while (0)
/* 71 ADC izy */
#define OPC_71(o_) do { uint8_t p_ = (uint8_t)(o_); uint16_t b_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 4); uint8_t m_ = RD(ea_, 4 + px_); op_adc(m_); C.clk += 5 + px_; } while (0)
/* 73 RRA izy */
#define OPC_73(o_) do { uint8_t p_ = (uint8_t)(o_); uint16_t b_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 4); uint8_t m_ = RD(ea_, 5); DWR(ea_, m_, 6); m_ = op_rra(m_); WR(ea_, m_, 7); C.clk += 8; } while (0)
/* 74 NOP zpx */
#define OPC_74(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); (void)m_; C.clk += 4; } while (0)
/* 75 ADC zpx */
#define OPC_75(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); op_adc(m_); C.clk += 4; } while (0)
/* 76 ROR zpx */
#define OPC_76(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); m_ = op_ror(m_); ZWR(ea_, m_); C.clk += 6; } while (0)
/* 77 RRA zpx */
#define OPC_77(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); m_ = op_rra(m_); ZWR(ea_, m_); C.clk += 6; } while (0)
/* 78 SEI imp */
#define OPC_78() do { C.cpu.fi = 1; C.clk += 2; } while (0)
/* 79 ADC aby */
#define OPC_79(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); op_adc(m_); C.clk += 4 + px_; } while (0)
/* 7A NOP imp */
#define OPC_7A() do {  C.clk += 2; } while (0)
/* 7B RRA aby */
#define OPC_7B(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_rra(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* 7C NOP abx */
#define OPC_7C(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); (void)m_; C.clk += 4 + px_; } while (0)
/* 7D ADC abx */
#define OPC_7D(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); op_adc(m_); C.clk += 4 + px_; } while (0)
/* 7E ROR abx */
#define OPC_7E(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_ror(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* 7F RRA abx */
#define OPC_7F(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_rra(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* 80 NOP imm */
#define OPC_80(o_) do { uint8_t m_ = (uint8_t)(o_); (void)m_; C.clk += 2; } while (0)
/* 81 STA izx */
#define OPC_81(o_) do { uint8_t p_ = (uint8_t)((o_) + C.cpu.x); uint16_t ea_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); WR(ea_, C.cpu.a, 5); C.clk += 6; } while (0)
/* 82 NOP imm */
#define OPC_82(o_) do { uint8_t m_ = (uint8_t)(o_); (void)m_; C.clk += 2; } while (0)
/* 83 SAX izx */
#define OPC_83(o_) do { uint8_t p_ = (uint8_t)((o_) + C.cpu.x); uint16_t ea_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); WR(ea_, (uint8_t)(C.cpu.a & C.cpu.x), 5); C.clk += 6; } while (0)
/* 84 STY zp */
#define OPC_84(o_) do { uint8_t ea_ = (uint8_t)(o_); ZWR(ea_, C.cpu.y); C.clk += 3; } while (0)
/* 85 STA zp */
#define OPC_85(o_) do { uint8_t ea_ = (uint8_t)(o_); ZWR(ea_, C.cpu.a); C.clk += 3; } while (0)
/* 86 STX zp */
#define OPC_86(o_) do { uint8_t ea_ = (uint8_t)(o_); ZWR(ea_, C.cpu.x); C.clk += 3; } while (0)
/* 87 SAX zp */
#define OPC_87(o_) do { uint8_t ea_ = (uint8_t)(o_); ZWR(ea_, (uint8_t)(C.cpu.a & C.cpu.x)); C.clk += 3; } while (0)
/* 88 DEY imp */
#define OPC_88() do { C.cpu.y--; SETNZ(C.cpu.y); C.clk += 2; } while (0)
/* 89 NOP imm */
#define OPC_89(o_) do { uint8_t m_ = (uint8_t)(o_); (void)m_; C.clk += 2; } while (0)
/* 8A TXA imp */
#define OPC_8A() do { C.cpu.a = C.cpu.x; SETNZ(C.cpu.a); C.clk += 2; } while (0)
/* 8B XAA imm */
#define OPC_8B(o_) do { uint8_t m_ = (uint8_t)(o_); C.cpu.a = (uint8_t)((C.cpu.a | 0xEE) & C.cpu.x & m_); SETNZ(C.cpu.a); C.clk += 2; } while (0)
/* 8C STY abs */
#define OPC_8C(o_) do { uint16_t ea_ = (uint16_t)(o_); WR(ea_, C.cpu.y, 3); C.clk += 4; } while (0)
/* 8D STA abs */
#define OPC_8D(o_) do { uint16_t ea_ = (uint16_t)(o_); WR(ea_, C.cpu.a, 3); C.clk += 4; } while (0)
/* 8E STX abs */
#define OPC_8E(o_) do { uint16_t ea_ = (uint16_t)(o_); WR(ea_, C.cpu.x, 3); C.clk += 4; } while (0)
/* 8F SAX abs */
#define OPC_8F(o_) do { uint16_t ea_ = (uint16_t)(o_); WR(ea_, (uint8_t)(C.cpu.a & C.cpu.x), 3); C.clk += 4; } while (0)
/* 91 STA izy */
#define OPC_91(o_) do { uint8_t p_ = (uint8_t)(o_); uint16_t b_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 4); WR(ea_, C.cpu.a, 5); C.clk += 6; } while (0)
/* 93 SHA izy */
#define OPC_93(o_) do { uint8_t p_ = (uint8_t)(o_); uint16_t b_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 4); uint8_t v_ = (uint8_t)((C.cpu.a & C.cpu.x) & (uint8_t)((b_ >> 8) + 1)); uint16_t wa_ = px_ ? (uint16_t)((v_ << 8) | (ea_ & 0xFF)) : ea_; WR(wa_, v_, 5); C.clk += 6; } while (0)
/* 94 STY zpx */
#define OPC_94(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); ZWR(ea_, C.cpu.y); C.clk += 4; } while (0)
/* 95 STA zpx */
#define OPC_95(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); ZWR(ea_, C.cpu.a); C.clk += 4; } while (0)
/* 96 STX zpy */
#define OPC_96(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.y); ZWR(ea_, C.cpu.x); C.clk += 4; } while (0)
/* 97 SAX zpy */
#define OPC_97(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.y); ZWR(ea_, (uint8_t)(C.cpu.a & C.cpu.x)); C.clk += 4; } while (0)
/* 98 TYA imp */
#define OPC_98() do { C.cpu.a = C.cpu.y; SETNZ(C.cpu.a); C.clk += 2; } while (0)
/* 99 STA aby */
#define OPC_99(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); WR(ea_, C.cpu.a, 4); C.clk += 5; } while (0)
/* 9A TXS imp */
#define OPC_9A() do { C.cpu.sp = C.cpu.x; C.clk += 2; } while (0)
/* 9B TAS aby */
#define OPC_9B(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); C.cpu.sp = (uint8_t)(C.cpu.a & C.cpu.x); uint8_t v_ = (uint8_t)((C.cpu.sp) & (uint8_t)((b_ >> 8) + 1)); uint16_t wa_ = px_ ? (uint16_t)((v_ << 8) | (ea_ & 0xFF)) : ea_; WR(wa_, v_, 4); C.clk += 5; } while (0)
/* 9C SHY abx */
#define OPC_9C(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t v_ = (uint8_t)((C.cpu.y) & (uint8_t)((b_ >> 8) + 1)); uint16_t wa_ = px_ ? (uint16_t)((v_ << 8) | (ea_ & 0xFF)) : ea_; WR(wa_, v_, 4); C.clk += 5; } while (0)
/* 9D STA abx */
#define OPC_9D(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); WR(ea_, C.cpu.a, 4); C.clk += 5; } while (0)
/* 9E SHX aby */
#define OPC_9E(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t v_ = (uint8_t)((C.cpu.x) & (uint8_t)((b_ >> 8) + 1)); uint16_t wa_ = px_ ? (uint16_t)((v_ << 8) | (ea_ & 0xFF)) : ea_; WR(wa_, v_, 4); C.clk += 5; } while (0)
/* 9F SHA aby */
#define OPC_9F(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t v_ = (uint8_t)((C.cpu.a & C.cpu.x) & (uint8_t)((b_ >> 8) + 1)); uint16_t wa_ = px_ ? (uint16_t)((v_ << 8) | (ea_ & 0xFF)) : ea_; WR(wa_, v_, 4); C.clk += 5; } while (0)
/* A0 LDY imm */
#define OPC_A0(o_) do { uint8_t m_ = (uint8_t)(o_); C.cpu.y = m_; SETNZ(m_); C.clk += 2; } while (0)
/* A1 LDA izx */
#define OPC_A1(o_) do { uint8_t p_ = (uint8_t)((o_) + C.cpu.x); uint16_t ea_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint8_t m_ = RD(ea_, 5); C.cpu.a = m_; SETNZ(m_); C.clk += 6; } while (0)
/* A2 LDX imm */
#define OPC_A2(o_) do { uint8_t m_ = (uint8_t)(o_); C.cpu.x = m_; SETNZ(m_); C.clk += 2; } while (0)
/* A3 LAX izx */
#define OPC_A3(o_) do { uint8_t p_ = (uint8_t)((o_) + C.cpu.x); uint16_t ea_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint8_t m_ = RD(ea_, 5); C.cpu.a = C.cpu.x = m_; SETNZ(m_); C.clk += 6; } while (0)
/* A4 LDY zp */
#define OPC_A4(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); C.cpu.y = m_; SETNZ(m_); C.clk += 3; } while (0)
/* A5 LDA zp */
#define OPC_A5(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); C.cpu.a = m_; SETNZ(m_); C.clk += 3; } while (0)
/* A6 LDX zp */
#define OPC_A6(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); C.cpu.x = m_; SETNZ(m_); C.clk += 3; } while (0)
/* A7 LAX zp */
#define OPC_A7(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); C.cpu.a = C.cpu.x = m_; SETNZ(m_); C.clk += 3; } while (0)
/* A8 TAY imp */
#define OPC_A8() do { C.cpu.y = C.cpu.a; SETNZ(C.cpu.y); C.clk += 2; } while (0)
/* A9 LDA imm */
#define OPC_A9(o_) do { uint8_t m_ = (uint8_t)(o_); C.cpu.a = m_; SETNZ(m_); C.clk += 2; } while (0)
/* AA TAX imp */
#define OPC_AA() do { C.cpu.x = C.cpu.a; SETNZ(C.cpu.x); C.clk += 2; } while (0)
/* AB LXA imm */
#define OPC_AB(o_) do { uint8_t m_ = (uint8_t)(o_); C.cpu.a = C.cpu.x = (uint8_t)((C.cpu.a | 0xEE) & m_); SETNZ(C.cpu.a); C.clk += 2; } while (0)
/* AC LDY abs */
#define OPC_AC(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); C.cpu.y = m_; SETNZ(m_); C.clk += 4; } while (0)
/* AD LDA abs */
#define OPC_AD(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); C.cpu.a = m_; SETNZ(m_); C.clk += 4; } while (0)
/* AE LDX abs */
#define OPC_AE(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); C.cpu.x = m_; SETNZ(m_); C.clk += 4; } while (0)
/* AF LAX abs */
#define OPC_AF(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); C.cpu.a = C.cpu.x = m_; SETNZ(m_); C.clk += 4; } while (0)
/* B1 LDA izy */
#define OPC_B1(o_) do { uint8_t p_ = (uint8_t)(o_); uint16_t b_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 4); uint8_t m_ = RD(ea_, 4 + px_); C.cpu.a = m_; SETNZ(m_); C.clk += 5 + px_; } while (0)
/* B3 LAX izy */
#define OPC_B3(o_) do { uint8_t p_ = (uint8_t)(o_); uint16_t b_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 4); uint8_t m_ = RD(ea_, 4 + px_); C.cpu.a = C.cpu.x = m_; SETNZ(m_); C.clk += 5 + px_; } while (0)
/* B4 LDY zpx */
#define OPC_B4(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); C.cpu.y = m_; SETNZ(m_); C.clk += 4; } while (0)
/* B5 LDA zpx */
#define OPC_B5(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); C.cpu.a = m_; SETNZ(m_); C.clk += 4; } while (0)
/* B6 LDX zpy */
#define OPC_B6(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.y); uint8_t m_ = ZRD(ea_); C.cpu.x = m_; SETNZ(m_); C.clk += 4; } while (0)
/* B7 LAX zpy */
#define OPC_B7(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.y); uint8_t m_ = ZRD(ea_); C.cpu.a = C.cpu.x = m_; SETNZ(m_); C.clk += 4; } while (0)
/* B8 CLV imp */
#define OPC_B8() do { C.cpu.fv = 0; C.clk += 2; } while (0)
/* B9 LDA aby */
#define OPC_B9(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); C.cpu.a = m_; SETNZ(m_); C.clk += 4 + px_; } while (0)
/* BA TSX imp */
#define OPC_BA() do { C.cpu.x = C.cpu.sp; SETNZ(C.cpu.x); C.clk += 2; } while (0)
/* BB LAS aby */
#define OPC_BB(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); { uint8_t t_ = (uint8_t)(m_ & C.cpu.sp); C.cpu.a = C.cpu.x = C.cpu.sp = t_; SETNZ(t_); } C.clk += 4 + px_; } while (0)
/* BC LDY abx */
#define OPC_BC(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); C.cpu.y = m_; SETNZ(m_); C.clk += 4 + px_; } while (0)
/* BD LDA abx */
#define OPC_BD(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); C.cpu.a = m_; SETNZ(m_); C.clk += 4 + px_; } while (0)
/* BE LDX aby */
#define OPC_BE(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); C.cpu.x = m_; SETNZ(m_); C.clk += 4 + px_; } while (0)
/* BF LAX aby */
#define OPC_BF(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); C.cpu.a = C.cpu.x = m_; SETNZ(m_); C.clk += 4 + px_; } while (0)
/* C0 CPY imm */
#define OPC_C0(o_) do { uint8_t m_ = (uint8_t)(o_); op_cmp(C.cpu.y, m_); C.clk += 2; } while (0)
/* C1 CMP izx */
#define OPC_C1(o_) do { uint8_t p_ = (uint8_t)((o_) + C.cpu.x); uint16_t ea_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint8_t m_ = RD(ea_, 5); op_cmp(C.cpu.a, m_); C.clk += 6; } while (0)
/* C2 NOP imm */
#define OPC_C2(o_) do { uint8_t m_ = (uint8_t)(o_); (void)m_; C.clk += 2; } while (0)
/* C3 DCP izx */
#define OPC_C3(o_) do { uint8_t p_ = (uint8_t)((o_) + C.cpu.x); uint16_t ea_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint8_t m_ = RD(ea_, 5); DWR(ea_, m_, 6); m_ = op_dcp(m_); WR(ea_, m_, 7); C.clk += 8; } while (0)
/* C4 CPY zp */
#define OPC_C4(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); op_cmp(C.cpu.y, m_); C.clk += 3; } while (0)
/* C5 CMP zp */
#define OPC_C5(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); op_cmp(C.cpu.a, m_); C.clk += 3; } while (0)
/* C6 DEC zp */
#define OPC_C6(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); m_ = op_dec(m_); ZWR(ea_, m_); C.clk += 5; } while (0)
/* C7 DCP zp */
#define OPC_C7(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); m_ = op_dcp(m_); ZWR(ea_, m_); C.clk += 5; } while (0)
/* C8 INY imp */
#define OPC_C8() do { C.cpu.y++; SETNZ(C.cpu.y); C.clk += 2; } while (0)
/* C9 CMP imm */
#define OPC_C9(o_) do { uint8_t m_ = (uint8_t)(o_); op_cmp(C.cpu.a, m_); C.clk += 2; } while (0)
/* CA DEX imp */
#define OPC_CA() do { C.cpu.x--; SETNZ(C.cpu.x); C.clk += 2; } while (0)
/* CB SBX imm */
#define OPC_CB(o_) do { uint8_t m_ = (uint8_t)(o_); { unsigned t_ = (unsigned)(C.cpu.a & C.cpu.x) - m_; C.cpu.fc = t_ < 0x100u; C.cpu.x = (uint8_t)t_; SETNZ(C.cpu.x); } C.clk += 2; } while (0)
/* CC CPY abs */
#define OPC_CC(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); op_cmp(C.cpu.y, m_); C.clk += 4; } while (0)
/* CD CMP abs */
#define OPC_CD(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); op_cmp(C.cpu.a, m_); C.clk += 4; } while (0)
/* CE DEC abs */
#define OPC_CE(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); DWR(ea_, m_, 4); m_ = op_dec(m_); WR(ea_, m_, 5); C.clk += 6; } while (0)
/* CF DCP abs */
#define OPC_CF(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); DWR(ea_, m_, 4); m_ = op_dcp(m_); WR(ea_, m_, 5); C.clk += 6; } while (0)
/* D1 CMP izy */
#define OPC_D1(o_) do { uint8_t p_ = (uint8_t)(o_); uint16_t b_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 4); uint8_t m_ = RD(ea_, 4 + px_); op_cmp(C.cpu.a, m_); C.clk += 5 + px_; } while (0)
/* D3 DCP izy */
#define OPC_D3(o_) do { uint8_t p_ = (uint8_t)(o_); uint16_t b_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 4); uint8_t m_ = RD(ea_, 5); DWR(ea_, m_, 6); m_ = op_dcp(m_); WR(ea_, m_, 7); C.clk += 8; } while (0)
/* D4 NOP zpx */
#define OPC_D4(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); (void)m_; C.clk += 4; } while (0)
/* D5 CMP zpx */
#define OPC_D5(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); op_cmp(C.cpu.a, m_); C.clk += 4; } while (0)
/* D6 DEC zpx */
#define OPC_D6(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); m_ = op_dec(m_); ZWR(ea_, m_); C.clk += 6; } while (0)
/* D7 DCP zpx */
#define OPC_D7(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); m_ = op_dcp(m_); ZWR(ea_, m_); C.clk += 6; } while (0)
/* D8 CLD imp */
#define OPC_D8() do { C.cpu.fd = 0; C.clk += 2; } while (0)
/* D9 CMP aby */
#define OPC_D9(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); op_cmp(C.cpu.a, m_); C.clk += 4 + px_; } while (0)
/* DA NOP imp */
#define OPC_DA() do {  C.clk += 2; } while (0)
/* DB DCP aby */
#define OPC_DB(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_dcp(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* DC NOP abx */
#define OPC_DC(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); (void)m_; C.clk += 4 + px_; } while (0)
/* DD CMP abx */
#define OPC_DD(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); op_cmp(C.cpu.a, m_); C.clk += 4 + px_; } while (0)
/* DE DEC abx */
#define OPC_DE(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_dec(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* DF DCP abx */
#define OPC_DF(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_dcp(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* E0 CPX imm */
#define OPC_E0(o_) do { uint8_t m_ = (uint8_t)(o_); op_cmp(C.cpu.x, m_); C.clk += 2; } while (0)
/* E1 SBC izx */
#define OPC_E1(o_) do { uint8_t p_ = (uint8_t)((o_) + C.cpu.x); uint16_t ea_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint8_t m_ = RD(ea_, 5); op_sbc(m_); C.clk += 6; } while (0)
/* E2 NOP imm */
#define OPC_E2(o_) do { uint8_t m_ = (uint8_t)(o_); (void)m_; C.clk += 2; } while (0)
/* E3 ISC izx */
#define OPC_E3(o_) do { uint8_t p_ = (uint8_t)((o_) + C.cpu.x); uint16_t ea_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint8_t m_ = RD(ea_, 5); DWR(ea_, m_, 6); m_ = op_isc(m_); WR(ea_, m_, 7); C.clk += 8; } while (0)
/* E4 CPX zp */
#define OPC_E4(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); op_cmp(C.cpu.x, m_); C.clk += 3; } while (0)
/* E5 SBC zp */
#define OPC_E5(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); op_sbc(m_); C.clk += 3; } while (0)
/* E6 INC zp */
#define OPC_E6(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); m_ = op_inc(m_); ZWR(ea_, m_); C.clk += 5; } while (0)
/* E7 ISC zp */
#define OPC_E7(o_) do { uint8_t ea_ = (uint8_t)(o_); uint8_t m_ = ZRD(ea_); m_ = op_isc(m_); ZWR(ea_, m_); C.clk += 5; } while (0)
/* E8 INX imp */
#define OPC_E8() do { C.cpu.x++; SETNZ(C.cpu.x); C.clk += 2; } while (0)
/* E9 SBC imm */
#define OPC_E9(o_) do { uint8_t m_ = (uint8_t)(o_); op_sbc(m_); C.clk += 2; } while (0)
/* EA NOP imp */
#define OPC_EA() do {  C.clk += 2; } while (0)
/* EB SBC imm */
#define OPC_EB(o_) do { uint8_t m_ = (uint8_t)(o_); op_sbc(m_); C.clk += 2; } while (0)
/* EC CPX abs */
#define OPC_EC(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); op_cmp(C.cpu.x, m_); C.clk += 4; } while (0)
/* ED SBC abs */
#define OPC_ED(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); op_sbc(m_); C.clk += 4; } while (0)
/* EE INC abs */
#define OPC_EE(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); DWR(ea_, m_, 4); m_ = op_inc(m_); WR(ea_, m_, 5); C.clk += 6; } while (0)
/* EF ISC abs */
#define OPC_EF(o_) do { uint16_t ea_ = (uint16_t)(o_); uint8_t m_ = RD(ea_, 3); DWR(ea_, m_, 4); m_ = op_isc(m_); WR(ea_, m_, 5); C.clk += 6; } while (0)
/* F1 SBC izy */
#define OPC_F1(o_) do { uint8_t p_ = (uint8_t)(o_); uint16_t b_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 4); uint8_t m_ = RD(ea_, 4 + px_); op_sbc(m_); C.clk += 5 + px_; } while (0)
/* F3 ISC izy */
#define OPC_F3(o_) do { uint8_t p_ = (uint8_t)(o_); uint16_t b_ = (uint16_t)(ZRD(p_) | (ZRD((uint8_t)(p_ + 1)) << 8)); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 4); uint8_t m_ = RD(ea_, 5); DWR(ea_, m_, 6); m_ = op_isc(m_); WR(ea_, m_, 7); C.clk += 8; } while (0)
/* F4 NOP zpx */
#define OPC_F4(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); (void)m_; C.clk += 4; } while (0)
/* F5 SBC zpx */
#define OPC_F5(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); op_sbc(m_); C.clk += 4; } while (0)
/* F6 INC zpx */
#define OPC_F6(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); m_ = op_inc(m_); ZWR(ea_, m_); C.clk += 6; } while (0)
/* F7 ISC zpx */
#define OPC_F7(o_) do { uint8_t ea_ = (uint8_t)((o_) + C.cpu.x); uint8_t m_ = ZRD(ea_); m_ = op_isc(m_); ZWR(ea_, m_); C.clk += 6; } while (0)
/* F8 SED imp */
#define OPC_F8() do { C.cpu.fd = 1; C.clk += 2; } while (0)
/* F9 SBC aby */
#define OPC_F9(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); op_sbc(m_); C.clk += 4 + px_; } while (0)
/* FA NOP imp */
#define OPC_FA() do {  C.clk += 2; } while (0)
/* FB ISC aby */
#define OPC_FB(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.y); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_isc(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* FC NOP abx */
#define OPC_FC(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); (void)m_; C.clk += 4 + px_; } while (0)
/* FD SBC abx */
#define OPC_FD(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; if (px_) DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 3 + px_); op_sbc(m_); C.clk += 4 + px_; } while (0)
/* FE INC abx */
#define OPC_FE(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_inc(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)
/* FF ISC abx */
#define OPC_FF(o_) do { uint16_t b_ = (uint16_t)(o_); uint16_t ea_ = (uint16_t)(b_ + C.cpu.x); unsigned px_ = ((unsigned)(b_ ^ ea_) >> 8) & 1u; (void)px_; DRD((uint16_t)((b_ & 0xFF00) | (ea_ & 0x00FF)), 3); uint8_t m_ = RD(ea_, 4); DWR(ea_, m_, 5); m_ = op_isc(m_); WR(ea_, m_, 6); C.clk += 7; } while (0)

/* instruction length by opcode */
#define LJ_OPLEN_TABLE { \
    1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, \
    2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 1, 3, 3, 3, 3, 3, \
    3, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, \
    2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 1, 3, 3, 3, 3, 3, \
    1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, \
    2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 1, 3, 3, 3, 3, 3, \
    1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, \
    2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 1, 3, 3, 3, 3, 3, \
    2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, \
    2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 1, 3, 3, 3, 3, 3, \
    2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, \
    2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 1, 3, 3, 3, 3, 3, \
    2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, \
    2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 1, 3, 3, 3, 3, 3, \
    2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, \
    2, 2, 1, 2, 2, 2, 2, 2, 1, 3, 1, 3, 3, 3, 3, 3, \
}

#endif
