/*
 * lj_game.c - start the game from the image generated by tools/ljrecomp
 * (build/gen/lj_game_data.c) and register the recompiled instructions.
 */
#include <string.h>
#include "c64.h"

extern const uint16_t lj_game_load;
extern const uint16_t lj_game_entry;
extern const char lj_game_release[];
extern const char lj_game_hash[];
extern const uint32_t lj_game_image_len;
extern const uint8_t lj_game_image[];
extern const uint32_t lj_code_count;
extern const uint16_t lj_code_addr[];
extern const uint8_t lj_code_info[];

int lj_recomp_enabled = 1;

int lj_game_init(int sample_rate)
{
    lj_power_on(sample_rate);
    if ((uint32_t)lj_game_load + lj_game_image_len > 0x10000)
        return -1;
    memcpy(&C.ram[lj_game_load], lj_game_image, lj_game_image_len);
    /* end of the loaded file, as the KERNAL LOAD routine leaves it */
    uint16_t end = (uint16_t)(lj_game_load + lj_game_image_len);
    C.ram[0xAE] = (uint8_t)end;
    C.ram[0xAF] = (uint8_t)(end >> 8);
    C.ram[0x2D] = C.ram[0x2F] = C.ram[0x31] = (uint8_t)end;
    C.ram[0x2E] = C.ram[0x30] = C.ram[0x32] = (uint8_t)(end >> 8);
    lj_extras_check();
    if (recomp_available && lj_recomp_enabled) {
        for (uint32_t i = 0; i < lj_code_count; i++) {
            uint16_t a = lj_code_addr[i];
            uint8_t len = lj_code_info[i] & 0x0F;
            int dyn = (lj_code_info[i] & 0x80) != 0;
            mem_mark_code_bytes(a, len, dyn, &lj_game_image[a - lj_game_load]);
        }
    }
    lj_start(lj_game_entry);
    return 0;
}

const char *lj_game_version(void) { return lj_game_release; }
